// Generated by scripts/gen-asset-manifest.mjs — do not edit by hand.
// Every PNG under public/assets, by category. Add or remove a file and
// rerun `npm run gen:assets` (it also runs on install and before a build).

export const assetManifest = {
  battlebg: ['default', 'boss', 'cave', 'ruins'],
  bosses: ['default', 'guardian'],
  enemies: ['default', 'goblin', 'slime', 'wraith'],
  events: ['default', 'bossroom', 'branch', 'discovery', 'empty', 'special'],
  locations: ['default', 'cave', 'forest', 'ruins'],
  scenes: ['default', 'dkp_2way', 'dkp_battle', 'dkp_bossBattle', 'dkp_coridoor1', 'dkp_coridoor2', 'dkp_keyRoom', 'dkp_restRoom', 'dkp_shrine', 'dkp_trapRoom', 'dkp_treasureRoom'],
  spells: ['default', 'arcane', 'earth', 'fire', 'water', 'wind'],
  totems: ['default', 'totem_ember', 'totem_silverKnight', 'totem_stone', 'totem_tide'],
  traps: ['default', 'sprung'],
  treasure: ['default', 'locked', 'open', 'rest', 'shrine'],
} as const
